#!/bin/bash

function indent {
  echo ":: $*"
}

export dir=$(readlink -f $(dirname $0))
export wallpaper_dir=${wallpaper_dir:-~/.wallpapers/}

prog=$1
shift

case $prog in
  "add")
    $dir/add $*
    ;;
  "install")
    $dir/install
    ;;
  *)
    indent "$prog a not recognised directive"
    ;;
esac
