#!/bin/bash

enable=1

case $1 in
  "on")
    enable=1
    ;;
  "off")
    enable=0
    ;;
esac

if [[ enable -eq 1 ]]; then
  xset s off
  xset -dpms
  echo "Screen blanking enabled"
else
  xset s on
  xset +dpms
  echo "Screen blanking disabled"
fi
