#!/bin/bash -e

message="Restarting wireless"
logger $message
echo $message
notify-send "$message"

sudo systemctl restart netctl-auto@wlp3s0.service

status=$?

if [ $status -ne 0 ]; then
  echo "Failed"
  exit $status
else
  echo "Done"
fi

exit $status
